[package]
name = "kazeta-bios"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4.7", features = ["audio"] }
gilrs = "0.10.6"
futures = "0.3.30"
dirs = "5.0.1"
whoami = "1.4.1"
sysinfo = "0.30.5"
tar = "0.4.40"
walkdir = "2.4.0"
